name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    name: Build diff-metrics locally
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all
  test:
    name: Run diff-metrics locally
    permissions:
      issues: write
      pull-requests: write
      repository-projects: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repo
      - run: ls -la . && ls -la dist
      - uses: ./
        name: Diff Metrics
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          ts-roots: |
            src
